### ISSUE TITLE
Initial setting

### ISSUE THREAD

**Issue by wewerk** [PatrikTrestik/homeassistant_nicegate#1]
First -  you've made a great job.
So far I used HomeKit device integration but I'm not satisfied with the performance. The IT4WIFI device is very unstable.
I hope that your integration will remedy the problems.
Can you help me with the initial setting, please ?  I know the IP and MAC address of the IT4WIFI device but no user and password.
Thank you.
David.

**Comment by PatrikTrestik** [comment]
Hi. Actually it was experiment which turned out to be working. I finished it to state where it works for me and there are no obvious bugs.

Initial connection is not ready yet. I was hesitant to do the work if I'm only one using it 😄 But if we are two, I'll resume work.

If you want it to have it connected immediately here is how:
1) You must have working Nice app in mobile. You as first user (one who did initial setup) are admin and you have to authorize all other users.
2) You have to be able to run python script.
3) I'll provide you script which generates new user and displays password
4) You have to authorize that user in Nice app.

Let me know if running python is option for you. Otherwise you have to wait till I'll integrate it here.

**Comment by wewerk** [comment]
Hi Patrik,
Yes - we are two now👍.
1. For initial setup as a Homekit device I used MyNice Welcome HK app. There is no such option for registering a user in this app. Maybe you mean MyNice Pro app.
2. No prob. , I have here virtual machine with python3 installed.
3. Yes, please.
4. I will do my best.
Thank You.
P.S. Podle Tvého jména usuzuji, že oba mluvíme stejnou řečí :-)

**Comment by PatrikTrestik** [comment]
> Hi Patrik, Yes - we are two now👍.
> 
> 1. For initial setup as a Homekit device I used MyNice Welcome HK app. There is no such option for registering a user in this app. Maybe you mean MyNice Pro app.
> 2. No prob. , I have here virtual machine with python3 installed.
> 3. Yes, please.
> 4. I will do my best.
>    Thank You.
>    P.S. Podle Tvého jména usuzuji, že oba mluvíme stejnou řečí :-)

I found that there is one more part of initial pairing process misssing. I'll need to update script to be working for any device.
Instead of manual work, might be better that I'll finish setup part. Let's see tomorrow, I have some time for private projects.

P.S: Jasně 😄 Okolo HA potkávám spoustu Čechů. Ale tady to musím držet anglicky, aby to bylo pro větší publikum.
PM - patrikt (at) volny.cz

**Comment by PatrikTrestik** [comment]
I updated initial config flow. Try if you can connect.

**Comment by uchym2011** [comment]
Cześć,
Jak tam sytuacja z tą integracją?
Można się dołączyć?

**Comment by PatrikTrestik** [comment]
> Cześć, Jak tam sytuacja z tą integracją? Można się dołączyć?

Yes, sure. 
It is working for me for more than year. But I have no information if someone else is using it. 
Technically it works, but configuration flow requires some work to be user friendly.

Unfortunately I'll be off computer till mid December.

**Comment by apollon9** [comment]
Hi Patrick,

i came across your integration in search of something less complicated than the Homekit installation for the IT4WIFI.
Unfortunately, i can't pass the second site of the config flow (where the "setup code" is to be entered). 
The config flow stays at that site with "Unknown error occurred". I entered the code from the device in the form xxx-xx-xxx.

Looking closer to the HA logs:

"SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1018)"
```
Traceback (most recent call last):
  File "/config/custom_components/nicegate/nice_api.py", line 224, in pair
    reader, writer = await asyncio.open_connection(self.host, 443, ssl=ctx)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And another error (but may point to the identical problem):)

"Error handling request"
```
File "/config/custom_components/nicegate/config_flow.py", line 67, in async_step_pair
    user_input=await self.pair_device(self.data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nicegate/config_flow.py", line 119, in pair_device
    raise InvalidAuth
custom_components.nicegate.config_flow.InvalidAuth
```

Not having dug deeper yet, but is ist possible that (SSL) security updates in HA have outdated the method your integration interacts with the IT4WIFI bridge?

Thank you,
Leo

**Comment by PatrikTrestik** [comment]
I expect all issues mentioned here to be fixed. 

Closing.
